// locale-sdk-gen (Go) — generates a `const` block per namespace from the
// reference language's snapshot, so Go call sites reference typed key constants
// instead of stringly-typed literals.
//
//	LOCALE_SERVICE_ADDR=localhost:50051 go run . -scope=backend -lang=fa -out=./internal/i18nkeys
//
// fail-soft: if locale-service is unreachable but -out already exists, keep it
// and warn; otherwise exit non-zero.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	localeclient "github.com/txnet/i18n-platform/clients/go"
)

func main() {
	lang := flag.String("lang", "fa", "reference language (project standard: fa)")
	scope := flag.String("scope", "backend", "locale scope")
	out := flag.String("out", "./internal/i18nkeys", "output directory")
	addr := flag.String("addr", envOr("LOCALE_SERVICE_ADDR", "localhost:50051"), "locale-service address")
	flag.Parse()

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	client, err := localeclient.New(ctx, localeclient.Config{Addr: *addr, Scope: *scope, PreloadLangs: nil})
	var version string
	namespaces := map[string]map[string]string{}
	if err == nil {
		s, ferr := client.Snapshot(ctx, *lang)
		client.Close()
		if ferr != nil {
			err = ferr
		} else {
			version = s.GetVersion()
			for ns, data := range s.GetNamespaces() {
				namespaces[ns] = data.GetEntries()
			}
		}
	}

	if err != nil {
		if _, statErr := os.Stat(*out); statErr == nil {
			log.Printf("[locale-sdk-gen] locale-service (%s) unreachable; keeping %s. (%v)", *addr, *out, err)
			return
		}
		log.Fatalf("[locale-sdk-gen] locale-service unreachable and no previous %s: %v", *out, err)
	}

	if err := os.MkdirAll(*out, 0o755); err != nil {
		log.Fatal(err)
	}
	for ns, entries := range namespaces {
		keys := make([]string, 0, len(entries))
		for k := range entries {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		var b strings.Builder
		fmt.Fprintf(&b, "// AUTO-GENERATED by locale-sdk-gen — do not edit\n")
		fmt.Fprintf(&b, "// source: locale-service (%s), scope: %s, ref lang: %s, version: %s\n", *addr, *scope, *lang, version)
		fmt.Fprintf(&b, "package i18nkeys\n\nconst (\n")
		for _, k := range keys {
			fmt.Fprintf(&b, "\t%s = %q\n", constName(ns, k), k)
		}
		fmt.Fprint(&b, ")\n")

		file := filepath.Join(*out, strings.ReplaceAll(ns, "/", "_")+".go")
		if err := os.WriteFile(file, []byte(b.String()), 0o644); err != nil {
			log.Fatal(err)
		}
		log.Printf("[locale-sdk-gen] wrote %s (%d keys)", file, len(keys))
	}
}

func constName(ns, key string) string {
	parts := append(strings.FieldsFunc(ns, sep), strings.FieldsFunc(key, sep)...)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

func sep(r rune) bool { return r == '.' || r == '/' || r == '-' || r == '_' }

func envOr(k, d string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return d
}
