version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: txnet_${ENV_NAME}_prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT}:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    volumes:
      # مسیر خواندن کانفیگ بر اساس محیط تغییر می‌کند (config-prod یا config-dev)
      - ./config-${ENV_NAME}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - private_backend_network

  grafana:
    image: grafana/grafana:11.1.0
    container_name: txnet_${ENV_NAME}_grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      # آدرس دامنه متفاوت برای هر محیط
      - "traefik.http.routers.grafana_${ENV_NAME}.rule=Host(`${GRAFANA_ROUTER_HOST}`)"
      - "traefik.http.services.grafana_${ENV_NAME}.loadbalancer.server.port=3000"
    networks:
      - private_backend_network

  loki:
    image: grafana/loki:3.1.0
    container_name: txnet_${ENV_NAME}_loki
    restart: unless-stopped
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - private_backend_network

  promtail:
    image: grafana/promtail:3.1.0
    container_name: txnet_${ENV_NAME}_promtail
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config-${ENV_NAME}/promtail.yaml:/etc/promtail/promtail.yaml:ro
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - private_backend_network

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: txnet_${ENV_NAME}_alertmanager
    restart: unless-stopped
    ports:
      - "${ALERTMANAGER_PORT}:9093"
    volumes:
      - ./config-${ENV_NAME}/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - private_backend_network

# نام Volumeها به صورت خودکار توسط داکر و بر اساس Project Name مجزا می‌شوند
volumes:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  private_backend_network:
    external: true
    name: private_backend_network
