import { ConfigService } from '@nestjs/config';
import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { TokenService } from './token.service';

/**
 * Cross-language contract: a token minted by `TokenService.sign()` here must be
 * readable by `jwt.Validate` in `auth-handler` (Go), which sits in front of this
 * service as a Traefik ForwardAuth gateway.
 *
 * The two implementations share no code, only a wire format, so the contract is
 * pinned as a fixture: this spec writes it, and
 * `auth-handler/internal/jwt/contract_test.go` reads it back and validates it.
 * Keep the generated file committed — the Go side skips when it is missing.
 */
const FIXTURE = resolve(
  __dirname,
  '../../../../../contracts/jwt/ts-to-go.json',
);

const SECRET = 'contract-fixture-secret';
// Fixed, far in the future: the fixture is committed, so it must not rot.
const EXPIRES_AT = 4102444800; // 2100-01-01T00:00:00Z

/**
 * The clock is frozen so the fixture is byte-for-byte identical on every run.
 *
 * `TokenService.sign` stamps `iat` from the wall clock, so a fixture written
 * against the real time changed on every run and showed up as a modified file
 * in `git status` after `npm test` — which trains everyone to `git checkout`
 * it, including on the run where the wire format really did change. Frozen,
 * the file only moves when the token format does, and that diff means
 * something.
 */
const FROZEN_NOW_SEC = 1767225600; // 2026-01-01T00:00:00Z
jest.useFakeTimers({ now: FROZEN_NOW_SEC * 1000 });
afterAll(() => jest.useRealTimers());

const ttl = EXPIRES_AT - FROZEN_NOW_SEC;

// Every minted token has to outlive the commit, so the per-purpose TTLs are
// pinned to the same far-future expiry as the access token.
const configStub = {
  get: (key: string, fallback?: unknown) => {
    switch (key) {
      case 'JWT_ACCESS_SECRET':
        return SECRET;
      case 'JWT_ACCESS_TTL_SEC':
      case 'OTP_TOKEN_TTL_SEC':
      case 'RESET_TOKEN_TTL_SEC':
      case 'IMPERSONATION_TOKEN_TTL_SEC':
        return ttl;
      default:
        return fallback;
    }
  },
} as unknown as ConfigService;

describe('TokenService — auth-handler wire contract', () => {
  const tokens = new TokenService(configStub);

  const cases = {
    access: tokens.sign(
      {
        sub: 'user-contract-1',
        tenantId: 'tenant-contract-1',
        roleId: 'role-contract-1',
        permissions: ['user.read', 'billing.read'],
        sessionId: 'session-contract-1',
      },
      ttl,
    ),
    impersonated: tokens.signImpersonatedToken(
      {
        id: 'user-contract-2',
        tenantId: 'tenant-contract-1',
        roleId: 'role-contract-2',
        role: { rolePermissions: [{ permission: { key: 'user.read' } }] },
      },
      'session-contract-2',
      'admin-contract-1',
    ),
    expired: tokens.sign(
      {
        sub: 'user-contract-1',
        tenantId: 'tenant-contract-1',
        roleId: 'role-contract-1',
        permissions: [],
        sessionId: 'session-contract-1',
      },
      -60,
    ),
    otp: tokens.signOtpToken('user-contract-1'),
  };

  it('writes the fixture the Go contract test reads', () => {
    mkdirSync(dirname(FIXTURE), { recursive: true });
    writeFileSync(
      FIXTURE,
      `${JSON.stringify(
        {
          note:
            'Generated by txnet-backend/auth-service/src/app/auth/token.contract.spec.ts. ' +
            'Consumed by auth-handler/internal/jwt/contract_test.go. Do not hand-edit.',
          secret: SECRET,
          tokens: cases,
        },
        null,
        2,
      )}\n`,
    );

    expect(cases.access.split('.')).toHaveLength(3);
  });

  it('round-trips its own access token', () => {
    const claims = tokens.verify(cases.access);

    expect(claims.sub).toBe('user-contract-1');
    expect(claims.sessionId).toBe('session-contract-1');
    expect(claims.exp).toBe(EXPIRES_AT);
  });

  // The fixture is committed, so a short-lived token in it would start failing
  // on the Go side one TTL after it was generated.
  it('mints every non-expiry fixture with the pinned far-future exp', () => {
    for (const [name, token] of Object.entries(cases)) {
      if (name === 'expired') continue;

      const { exp } = JSON.parse(
        Buffer.from(token.split('.')[1], 'base64url').toString(),
      );
      expect([name, exp]).toEqual([name, EXPIRES_AT]);
    }
  });

  it('mints the expired fixture in the past', () => {
    const { exp } = JSON.parse(
      Buffer.from(cases.expired.split('.')[1], 'base64url').toString(),
    );
    expect(exp).toBeLessThan(FROZEN_NOW_SEC);
  });

  // The whole point of freezing the clock: two runs must produce the same
  // bytes, or the committed fixture is noise in every diff.
  it('stamps a fixed iat, so the committed fixture does not move on its own', () => {
    for (const token of Object.values(cases)) {
      const { iat } = JSON.parse(
        Buffer.from(token.split('.')[1], 'base64url').toString(),
      );
      expect(iat).toBe(FROZEN_NOW_SEC);
    }
  });

  // Every field the Go `Claims` struct unmarshals has to be present and named
  // exactly as Go expects, or it silently decodes to a zero value.
  it('emits the claim names auth-handler unmarshals', () => {
    const payload = JSON.parse(
      Buffer.from(cases.impersonated.split('.')[1], 'base64url').toString(),
    );

    expect(Object.keys(payload)).toEqual(
      expect.arrayContaining([
        'sub',
        'tenantId',
        'roleId',
        'sessionId',
        'permissions',
        'isImpersonated',
        'impersonatedBy',
        'exp',
      ]),
    );
  });

  // base64url, unpadded — Go decodes with base64.RawURLEncoding, which rejects
  // both '+/' and '=' padding.
  it('uses unpadded base64url for all three segments', () => {
    for (const segment of cases.access.split('.')) {
      expect(segment).toMatch(/^[A-Za-z0-9_-]+$/);
    }
  });
});
