version: "3.8"

services:
  gateway-handler:
    image: ${DOCKER_REGISTRY}/traefik:v3.7
    command:
      - "--api.dashboard=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=public_gateway_network"
      - "--entrypoints.web.address=:${TXNET_SITE_HTTP_PORT}"
      - "--entrypoints.websecure.address=:${TXNET_SITE_HTTPS_PORT}"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL_SSL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - target: ${TXNET_SITE_HTTP_PORT}
        published: ${TXNET_SITE_HTTP_PORT}
        protocol: tcp
        mode: host
      - target: ${TXNET_SITE_HTTPS_PORT}
        published: ${TXNET_SITE_HTTPS_PORT}
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./${ENVIRONMENT}_letsencrypt:/letsencrypt
    networks:
      - public_gateway_network
      - private_backend_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-http.rule=Host(`monitor.${DOMAIN_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      - "traefik.http.routers.dashboard-http.service=api@internal"
      - "traefik.http.routers.dashboard-http.middlewares=auth-dashboard"

      - "traefik.http.routers.dashboard-https.rule=Host(`monitor.${DOMAIN_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard-https.entrypoints=websecure"
      - "traefik.http.routers.dashboard-https.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard-https.service=api@internal"
      - "traefik.http.routers.dashboard-https.middlewares=auth-dashboard"

      - "traefik.http.middlewares.auth-dashboard.basicauth.users=${TRAEFIK_PANEL_USERNAME}:${TRAEFIK_PANEL_PASSWORD}"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M

  authorization-handler:
    image: ${DOCKER_REGISTRY}/authorization-handler:${ENVIRONMENT}
    build:
      context: ./auth-handler
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.my-auth.forwardauth.address=http://authorization-handler:${INTERAL_BACKEND_PORT}/validate"
      # اصلاح حرف «و» به کاما جهت تطابق استاندارد هدرها
      - "traefik.http.middlewares.my-auth.forwardauth.authResponseHeaders=X-User-Id,X-Actor-Id,X-User-Permissons"
      - "traefik.http.middlewares.strip-fake-headers.headers.customrequestheaders.X-User-Id="
      - "traefik.http.middlewares.strip-fake-headers.headers.customrequestheaders.X-Actor-Id="
      - "traefik.http.middlewares.strip-fake-headers.headers.customrequestheaders.X-User-Permissons="
    expose:
      - "${INTERAL_BACKEND_PORT}"
    volumes:
      - ./auth-handler:/app
    environment:
      - APP_ENV=${ENVIRONMENT}
      - APP_PORT=${INTERAL_BACKEND_PORT}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - private_backend_network
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role==worker"
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.2"
          memory: 256M

  # ==========================================
  # میکروسرویس‌های ساختار Nx Monorepo
  # ==========================================
  auth-service:
    image: txnet-auth-service:${ENVIRONMENT}
    build:
      context: ./txnet-backend
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
      args:
        - APP_NAME=auth-service
        - DOCKER_REGISTRY=${DOCKER_REGISTRY}
    labels:
      - "traefik.enable=true"
      # مسیر مپ شده به متدها و روت‌های این سرویس
      - "traefik.http.routers.auth-service.rule=Host(`api.${DOMAIN_NAME}`) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth-service.entrypoints=websecure"
      - "traefik.http.routers.auth-service.tls.certresolver=myresolver"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3000"
    volumes:
      - ./txnet-backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=${ENVIRONMENT}
      - DATABASE_URL=postgresql://${MAIN_DB_USERNAME}:${MAIN_DB_PASSWORD}@main-db:${MAIN_DB_PORT}/${MAIN_DB_NAME}
    networks:
      - private_backend_network
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role==worker"
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.2"
          memory: 256M

  billing-service:
    image: txnet-billing-service:${ENVIRONMENT}
    build:
      context: ./txnet-backend
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
      args:
        - APP_NAME=billing-service
        - DOCKER_REGISTRY=${DOCKER_REGISTRY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.billing-service.rule=Host(`api.${DOMAIN_NAME}`) && PathPrefix(`/api/billing`)"
      - "traefik.http.routers.billing-service.entrypoints=websecure"
      - "traefik.http.routers.billing-service.tls.certresolver=myresolver"
      # اعمال لایه امنیتی هدرها و احراز هویت ForwardAuth روی روت‌های مالی
      - "traefik.http.routers.billing-service.middlewares=strip-fake-headers,my-auth"
      - "traefik.http.services.billing-service.loadbalancer.server.port=3000"
    volumes:
      - ./txnet-backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=${ENVIRONMENT}
    networks:
      - private_backend_network
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role==worker"
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.2"
          memory: 256M

  site-pwa:
    image: ${ENVIRONMENT}_site-pwa_${WEB_APP_VERSION}
    build:
      target: ${ENVIRONMENT}
      context: ./site-pwa
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}

    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${TXNET_SITE_PORT}
      - HOSTNAME=${DOMAIN_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_PORT=${REDIS_PORT}
      - MAIN_DB_USERNAME=${MAIN_DB_USERNAME}
      - MAIN_DB_PASSWORD=${MAIN_DB_PASSWORD}
      - DB_PORT=${MAIN_DB_PORT}
      - SMS_USERNAME=${SMS_USERNAME}
      - SMS_PASS=${SMS_PASS}
      - SMS_SENDER_PRIVATE=${SMS_SENDER_PRIVATE}
      - JWT_SECRET_CAPTCHA=${JWT_SECRET_CAPTCHA}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - NEXT_PUBLIC_PAYMENT_URL=${NEXT_PUBLIC_PAYMENT_URL}
    networks:
      - private_backend_network
    expose:
      - "${INTERAL_FRONTEND_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    dns:
      - 217.218.155.155
      - 217.218.127.127

    # هیچ پورتی به بیرون مپ نمی‌شود
    labels:
      - "traefik.enable=true"

      # ۱. تنظیم روتر برای دامنه اصلی (اجبار به استفاده از درگاه امن websecure)
      - "traefik.http.routers.nextjs.rule=Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls.certresolver=myresolver" # فعال‌سازی خودکار SSL Let's Encrypt

      # ۲. اتصال زنجیره میدل‌ورها به روتر
      - "traefik.http.routers.nextjs.middlewares=nextjs-compress, pwa-security, sw-cache-control"

      # ==========================================
      # میدل‌ور اول: فشرده‌سازی خودکار ترافیک (Gzip/Brotli)
      # ==========================================
      - "traefik.http.middlewares.nextjs-compress.compress=true"

      # ==========================================
      # میدل‌ور دوم: هدرهای امنیتی مرورگر برای PWA
      # ==========================================
      - "traefik.http.middlewares.pwa-security.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.pwa-security.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.pwa-security.headers.browserXssFilter=true"
      # فعال‌سازی HSTS برای اجبار مرورگر به استفاده از HTTPS تا یک سال آینده
      - "traefik.http.middlewares.pwa-security.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.pwa-security.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.pwa-security.headers.stsIncludeSubdomains=true"

      # ==========================================
      # میدل‌ور سوم: مدیریت کش هدرها برای جلوگیری از کش شدن Service Worker
      # ==========================================
      # این هدر به مرورگر می‌گوید فایل‌های حیاتی PWA را کش نکند تا آپدیت‌ها آنی اعمال شوند
      - "traefik.http.middlewares.sw-cache-control.headers.customResponseHeaders.Cache-Control=no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"

      # ==========================================
      # ارجاع ترافیک به پورت داخلی کانتینر Next.js
      # ==========================================
      - "traefik.http.services.nextjs.loadbalancer.server.port=${INTERAL_FRONTEND_PORT}"
    deploy:
      replicas: 2 # اجرای ۲ نسخه برای تقسیم بار (Load Balancing)
      placement:
        constraints:
          - "node.role==worker" # دور نگه داشتن بار پردازشی اپلیکیشن از منیجرها
      update_config:
        parallelism: 1
        delay: 15s # تاخیر ۱۵ ثانیه‌ای تا کانتینر جدید کاملا بالا بیاید و آماده پذیرش ترافیک شود
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "1.0" # حداکثر ۱ هسته سی‌پی‌یو
          memory: 1G # محدودیت رم برای جلوگیری از کرش کردن نود
        reservations:
          cpus: "0.2"
          memory: 256M
  memory-data:
    image: ${DOCKER_REGISTRY}/redis:8.8-alpine
    command: redis-server --save "" --requirepass ${REDIS_PASSWORD} --appendonly yes --appendfsync everysec
    volumes:
      - redis_vol_internal:/data
    networks:
      - private_backend_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.role==database"
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 1G

  main-db:
    image: ${DOCKER_REGISTRY}/postgres:18-alpine
    environment:
      - POSTGRES_USER=${MAIN_DB_USERNAME}
      - POSTGRES_PASSWORD=${MAIN_DB_PASSWORD}
      - POSTGRES_DB=${MAIN_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U $${MAIN_DB_USERNAME} -d $${MAIN_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - private_backend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.role==database"
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 1G

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mq-admin.rule=Host(`mq.${DOMAIN_NAME}`)"
      - "traefik.http.routers.mq-admin.entrypoints=websecure"
      - "traefik.http.routers.mq-admin.tls.certresolver=myresolver"
      - "traefik.http.services.mq-admin.loadbalancer.server.port=15672"
      - "traefik.http.routers.mq-admin.middlewares=auth-dashboard"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}!
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - private_backend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.role==database"
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 1G
  registry:
    image: registry:2
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - private_backend_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager" # برای حفظ یکپارچگی داده‌ها روی منیجر می‌ماند
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    labels:
      - "traefik.enable=true"
      # تعریف ساب‌دامین اختصاصی
      - "traefik.http.routers.registry.rule=Host(`registry.${DOMAIN_NAME}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=myresolver"

      # ارجاع به میدل‌ور احراز هویت
      - "traefik.http.routers.registry.middlewares=registry-auth"

      # پورت داخلی کانتینر ریجستری
      - "traefik.http.services.registry.loadbalancer.server.port=5000"

      # تنظیم یوزر و پسورد (پسورد باید هش شده باشد)
      - "traefik.http.middlewares.registry-auth.basicauth.users=${REGISTRY_AUTH_USER_PASS}"
volumes:
  txnetweb_db:
  txnetweb_log:
  redis_vol_internal:
  txnetweb_dbconfig:
  postgres_data:
  rabbitmq_data:
  registry_data:
networks:
  public_gateway_network:
    driver: overlay
    attachable: true
  private_backend_network:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1200
