services:
  authorization-handler:
    volumes:
      - ./auth-handler:/app
  auth-service:
    volumes:
      - ./txnet-backend:/app:delegated
      - /app/node_modules
  billing-service:
    volumes:
      - ./txnet-backend:/app:delegated
      - /app/node_modules
  site-pwa:
    volumes:
      - ./site-pwa:/app:delegated
      - /app/node_modules
