version: "3.8"

# Development overrides for local `docker compose` usage.
# Use together with the main `compose.yml`:
#   docker compose -f compose.yml -f docker-compose.dev.yml up --build

networks:
  public_gateway_network:
    driver: bridge
  private_backend_network:
    driver: bridge

services:
  gateway-handler:
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.network=public_gateway_network"
      - "--entrypoints.web.address=:${TXNET_SITE_HTTP_PORT}"
      - "--entrypoints.websecure.address=:${TXNET_SITE_HTTPS_PORT}"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL_SSL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:${TXNET_SITE_HTTP_PORT}"
      - "443:${TXNET_SITE_HTTPS_PORT}"
      - "${TXNET_SITE_HTTP_PORT}:${TXNET_SITE_HTTP_PORT}"
      - "${TXNET_SITE_HTTPS_PORT}:${TXNET_SITE_HTTPS_PORT}"
    volumes:
      - ./dev_letsencrypt:/letsencrypt
  authorization-handler:
    volumes:
      - ./auth-handler:/app
    deploy:
      replicas: 1
  auth-service:
    volumes:
      - ./txnet-backend:/app:delegated
      - /app/node_modules
    deploy:
      replicas: 1
  billing-service:
    volumes:
      - ./txnet-backend:/app:delegated
      - /app/node_modules
    deploy:
      replicas: 1
  site-pwa:
    volumes:
      - ./site-pwa:/app:delegated
      - /app/node_modules
      - /app/.next
    deploy:
      replicas: 1
