// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: locale/v1/locale.proto

package localev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocaleService_GetSnapshot_FullMethodName         = "/locale.v1.LocaleService/GetSnapshot"
	LocaleService_GetAvailableLocales_FullMethodName = "/locale.v1.LocaleService/GetAvailableLocales"
	LocaleService_Watch_FullMethodName               = "/locale.v1.LocaleService/Watch"
)

// LocaleServiceClient is the client API for LocaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocaleService is the source of truth for translations. It is a real gRPC
// service: unary RPCs for boot/metadata and a server-streaming RPC for live
// reload. Transport is HTTP/2 + protobuf binary.
type LocaleServiceClient interface {
	// Full snapshot of one language (optionally narrowed to a scope) — used for
	// the blocking boot of every consuming service.
	GetSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// Available languages + metadata (dir, native name, BCP-47 locale, ...).
	GetAvailableLocales(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailableLocalesResponse, error)
	// Live stream — the consumer stays connected and every change is pushed as a
	// full snapshot for the affected (lang, scope).
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateEvent], error)
}

type localeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocaleServiceClient(cc grpc.ClientConnInterface) LocaleServiceClient {
	return &localeServiceClient{cc}
}

func (c *localeServiceClient) GetSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, LocaleService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localeServiceClient) GetAvailableLocales(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AvailableLocalesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailableLocalesResponse)
	err := c.cc.Invoke(ctx, LocaleService_GetAvailableLocales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localeServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocaleService_ServiceDesc.Streams[0], LocaleService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, UpdateEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocaleService_WatchClient = grpc.ServerStreamingClient[UpdateEvent]

// LocaleServiceServer is the server API for LocaleService service.
// All implementations must embed UnimplementedLocaleServiceServer
// for forward compatibility.
//
// LocaleService is the source of truth for translations. It is a real gRPC
// service: unary RPCs for boot/metadata and a server-streaming RPC for live
// reload. Transport is HTTP/2 + protobuf binary.
type LocaleServiceServer interface {
	// Full snapshot of one language (optionally narrowed to a scope) — used for
	// the blocking boot of every consuming service.
	GetSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// Available languages + metadata (dir, native name, BCP-47 locale, ...).
	GetAvailableLocales(context.Context, *Empty) (*AvailableLocalesResponse, error)
	// Live stream — the consumer stays connected and every change is pushed as a
	// full snapshot for the affected (lang, scope).
	Watch(*WatchRequest, grpc.ServerStreamingServer[UpdateEvent]) error
	mustEmbedUnimplementedLocaleServiceServer()
}

// UnimplementedLocaleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocaleServiceServer struct{}

func (UnimplementedLocaleServiceServer) GetSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedLocaleServiceServer) GetAvailableLocales(context.Context, *Empty) (*AvailableLocalesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableLocales not implemented")
}
func (UnimplementedLocaleServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[UpdateEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedLocaleServiceServer) mustEmbedUnimplementedLocaleServiceServer() {}
func (UnimplementedLocaleServiceServer) testEmbeddedByValue()                       {}

// UnsafeLocaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocaleServiceServer will
// result in compilation errors.
type UnsafeLocaleServiceServer interface {
	mustEmbedUnimplementedLocaleServiceServer()
}

func RegisterLocaleServiceServer(s grpc.ServiceRegistrar, srv LocaleServiceServer) {
	// If the following call panics, it indicates UnimplementedLocaleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocaleService_ServiceDesc, srv)
}

func _LocaleService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocaleServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocaleService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocaleServiceServer).GetSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocaleService_GetAvailableLocales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocaleServiceServer).GetAvailableLocales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocaleService_GetAvailableLocales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocaleServiceServer).GetAvailableLocales(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocaleService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocaleServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, UpdateEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocaleService_WatchServer = grpc.ServerStreamingServer[UpdateEvent]

// LocaleService_ServiceDesc is the grpc.ServiceDesc for LocaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "locale.v1.LocaleService",
	HandlerType: (*LocaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _LocaleService_GetSnapshot_Handler,
		},
		{
			MethodName: "GetAvailableLocales",
			Handler:    _LocaleService_GetAvailableLocales_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _LocaleService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "locale/v1/locale.proto",
}
