// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: locale/v1/locale.proto

package localev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryState int32

const (
	EntryState_ENTRY_STATE_UNSPECIFIED EntryState = 0 // rejected: a write says what it is
	EntryState_ENTRY_STATE_PUBLISHED   EntryState = 1
	EntryState_ENTRY_STATE_DRAFT       EntryState = 2
)

// Enum value maps for EntryState.
var (
	EntryState_name = map[int32]string{
		0: "ENTRY_STATE_UNSPECIFIED",
		1: "ENTRY_STATE_PUBLISHED",
		2: "ENTRY_STATE_DRAFT",
	}
	EntryState_value = map[string]int32{
		"ENTRY_STATE_UNSPECIFIED": 0,
		"ENTRY_STATE_PUBLISHED":   1,
		"ENTRY_STATE_DRAFT":       2,
	}
)

func (x EntryState) Enum() *EntryState {
	p := new(EntryState)
	*p = x
	return p
}

func (x EntryState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryState) Descriptor() protoreflect.EnumDescriptor {
	return file_locale_v1_locale_proto_enumTypes[0].Descriptor()
}

func (EntryState) Type() protoreflect.EnumType {
	return &file_locale_v1_locale_proto_enumTypes[0]
}

func (x EntryState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryState.Descriptor instead.
func (EntryState) EnumDescriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{0}
}

type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Lang  string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	// "backend" | "frontend" | "shareds" | "" (empty = every scope merged, with
	// namespace keys prefixed by "<scope>/"). A named scope is always returned
	// together with the "shareds" namespaces.
	Scope         string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_locale_v1_locale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SnapshotRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type SnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Lang  string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Scope string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// sha1 over the whole (sorted) namespace/entry set for this (lang, scope).
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// namespace name -> flat entries
	Namespaces    map[string]*NamespaceData `protobuf:"bytes,4,rep,name=namespaces,proto3" json:"namespaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_locale_v1_locale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotResponse) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SnapshotResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SnapshotResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SnapshotResponse) GetNamespaces() map[string]*NamespaceData {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type NamespaceData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flat key (dot-notation for nested JSON) -> raw text (may contain {{var}}).
	Entries       map[string]string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceData) Reset() {
	*x = NamespaceData{}
	mi := &file_locale_v1_locale_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceData) ProtoMessage() {}

func (x *NamespaceData) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceData.ProtoReflect.Descriptor instead.
func (*NamespaceData) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{2}
}

func (x *NamespaceData) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only notify about these languages; empty = all.
	Langs []string `protobuf:"bytes,1,rep,name=langs,proto3" json:"langs,omitempty"`
	// Same meaning as SnapshotRequest.scope.
	Scope         string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_locale_v1_locale_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{3}
}

func (x *WatchRequest) GetLangs() []string {
	if x != nil {
		return x.Langs
	}
	return nil
}

func (x *WatchRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type UpdateEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Lang       string                 `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Scope      string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	NewVersion string                 `protobuf:"bytes,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	// Whole new snapshot (simpler and less buggy than deltas).
	FullSnapshot  *SnapshotResponse `protobuf:"bytes,4,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEvent) Reset() {
	*x = UpdateEvent{}
	mi := &file_locale_v1_locale_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEvent) ProtoMessage() {}

func (x *UpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEvent.ProtoReflect.Descriptor instead.
func (*UpdateEvent) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEvent) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *UpdateEvent) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *UpdateEvent) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *UpdateEvent) GetFullSnapshot() *SnapshotResponse {
	if x != nil {
		return x.FullSnapshot
	}
	return nil
}

type AvailableLocalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locales       []*LocaleMeta          `protobuf:"bytes,1,rep,name=locales,proto3" json:"locales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableLocalesResponse) Reset() {
	*x = AvailableLocalesResponse{}
	mi := &file_locale_v1_locale_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableLocalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableLocalesResponse) ProtoMessage() {}

func (x *AvailableLocalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableLocalesResponse.ProtoReflect.Descriptor instead.
func (*AvailableLocalesResponse) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{5}
}

func (x *AvailableLocalesResponse) GetLocales() []*LocaleMeta {
	if x != nil {
		return x.Locales
	}
	return nil
}

type LocaleMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                               // "fa"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // "Persian"
	ShortName     string                 `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`    // "FA"
	NativeName    string                 `protobuf:"bytes,4,opt,name=native_name,json=nativeName,proto3" json:"native_name,omitempty"` // "فارسی"
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`                                 // "rtl" | "ltr"
	Locale        string                 `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`                           // BCP-47, e.g. "fa-IR"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleMeta) Reset() {
	*x = LocaleMeta{}
	mi := &file_locale_v1_locale_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleMeta) ProtoMessage() {}

func (x *LocaleMeta) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleMeta.ProtoReflect.Descriptor instead.
func (*LocaleMeta) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{6}
}

func (x *LocaleMeta) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LocaleMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocaleMeta) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *LocaleMeta) GetNativeName() string {
	if x != nil {
		return x.NativeName
	}
	return ""
}

func (x *LocaleMeta) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *LocaleMeta) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type SetEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`         // "backend" | "frontend" | "shareds"
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`           // must exist in locales/
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"` // e.g. "catalog"
	Entries       map[string]string      `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	State         EntryState             `protobuf:"varint,5,opt,name=state,proto3,enum=locale.v1.EntryState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEntriesRequest) Reset() {
	*x = SetEntriesRequest{}
	mi := &file_locale_v1_locale_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntriesRequest) ProtoMessage() {}

func (x *SetEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntriesRequest.ProtoReflect.Descriptor instead.
func (*SetEntriesRequest) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{7}
}

func (x *SetEntriesRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SetEntriesRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SetEntriesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetEntriesRequest) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SetEntriesRequest) GetState() EntryState {
	if x != nil {
		return x.State
	}
	return EntryState_ENTRY_STATE_UNSPECIFIED
}

type SetEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       int32                  `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"` // non-empty entries written
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEntriesResponse) Reset() {
	*x = SetEntriesResponse{}
	mi := &file_locale_v1_locale_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntriesResponse) ProtoMessage() {}

func (x *SetEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntriesResponse.ProtoReflect.Descriptor instead.
func (*SetEntriesResponse) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{8}
}

func (x *SetEntriesResponse) GetWritten() int32 {
	if x != nil {
		return x.Written
	}
	return 0
}

type ListDraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,4,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDraftsRequest) Reset() {
	*x = ListDraftsRequest{}
	mi := &file_locale_v1_locale_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDraftsRequest) ProtoMessage() {}

func (x *ListDraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDraftsRequest.ProtoReflect.Descriptor instead.
func (*ListDraftsRequest) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{9}
}

func (x *ListDraftsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListDraftsRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ListDraftsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListDraftsRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

type DraftEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftEntry) Reset() {
	*x = DraftEntry{}
	mi := &file_locale_v1_locale_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftEntry) ProtoMessage() {}

func (x *DraftEntry) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftEntry.ProtoReflect.Descriptor instead.
func (*DraftEntry) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{10}
}

func (x *DraftEntry) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DraftEntry) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *DraftEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DraftEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DraftEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ListDraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drafts        []*DraftEntry          `protobuf:"bytes,1,rep,name=drafts,proto3" json:"drafts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDraftsResponse) Reset() {
	*x = ListDraftsResponse{}
	mi := &file_locale_v1_locale_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDraftsResponse) ProtoMessage() {}

func (x *ListDraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDraftsResponse.ProtoReflect.Descriptor instead.
func (*ListDraftsResponse) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{11}
}

func (x *ListDraftsResponse) GetDrafts() []*DraftEntry {
	if x != nil {
		return x.Drafts
	}
	return nil
}

type PublishDraftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Keys          []string               `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishDraftsRequest) Reset() {
	*x = PublishDraftsRequest{}
	mi := &file_locale_v1_locale_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishDraftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishDraftsRequest) ProtoMessage() {}

func (x *PublishDraftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishDraftsRequest.ProtoReflect.Descriptor instead.
func (*PublishDraftsRequest) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{12}
}

func (x *PublishDraftsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PublishDraftsRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *PublishDraftsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PublishDraftsRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PublishDraftsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Published     int32                  `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishDraftsResponse) Reset() {
	*x = PublishDraftsResponse{}
	mi := &file_locale_v1_locale_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishDraftsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishDraftsResponse) ProtoMessage() {}

func (x *PublishDraftsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishDraftsResponse.ProtoReflect.Descriptor instead.
func (*PublishDraftsResponse) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{13}
}

func (x *PublishDraftsResponse) GetPublished() int32 {
	if x != nil {
		return x.Published
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_locale_v1_locale_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_locale_v1_locale_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_locale_v1_locale_proto_rawDescGZIP(), []int{14}
}

var File_locale_v1_locale_proto protoreflect.FileDescriptor

const file_locale_v1_locale_proto_rawDesc = "" +
	"\n" +
	"\x16locale/v1/locale.proto\x12\tlocale.v1\";\n" +
	"\x0fSnapshotRequest\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"\xfc\x01\n" +
	"\x10SnapshotResponse\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12K\n" +
	"\n" +
	"namespaces\x18\x04 \x03(\v2+.locale.v1.SnapshotResponse.NamespacesEntryR\n" +
	"namespaces\x1aW\n" +
	"\x0fNamespacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.locale.v1.NamespaceDataR\x05value:\x028\x01\"\x8c\x01\n" +
	"\rNamespaceData\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.locale.v1.NamespaceData.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\fWatchRequest\x12\x14\n" +
	"\x05langs\x18\x01 \x03(\tR\x05langs\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"\x9a\x01\n" +
	"\vUpdateEvent\x12\x12\n" +
	"\x04lang\x18\x01 \x01(\tR\x04lang\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\tR\n" +
	"newVersion\x12@\n" +
	"\rfull_snapshot\x18\x04 \x01(\v2\x1b.locale.v1.SnapshotResponseR\ffullSnapshot\"K\n" +
	"\x18AvailableLocalesResponse\x12/\n" +
	"\alocales\x18\x01 \x03(\v2\x15.locale.v1.LocaleMetaR\alocales\"\x9e\x01\n" +
	"\n" +
	"LocaleMeta\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"short_name\x18\x03 \x01(\tR\tshortName\x12\x1f\n" +
	"\vnative_name\x18\x04 \x01(\tR\n" +
	"nativeName\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\x16\n" +
	"\x06locale\x18\x06 \x01(\tR\x06locale\"\x89\x02\n" +
	"\x11SetEntriesRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12C\n" +
	"\aentries\x18\x04 \x03(\v2).locale.v1.SetEntriesRequest.EntriesEntryR\aentries\x12+\n" +
	"\x05state\x18\x05 \x01(\x0e2\x15.locale.v1.EntryStateR\x05state\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x12SetEntriesResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\x05R\awritten\"z\n" +
	"\x11ListDraftsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x04 \x01(\tR\tkeyPrefix\"z\n" +
	"\n" +
	"DraftEntry\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\"C\n" +
	"\x12ListDraftsResponse\x12-\n" +
	"\x06drafts\x18\x01 \x03(\v2\x15.locale.v1.DraftEntryR\x06drafts\"r\n" +
	"\x14PublishDraftsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04keys\x18\x04 \x03(\tR\x04keys\"5\n" +
	"\x15PublishDraftsResponse\x12\x1c\n" +
	"\tpublished\x18\x01 \x01(\x05R\tpublished\"\a\n" +
	"\x05Empty*[\n" +
	"\n" +
	"EntryState\x12\x1b\n" +
	"\x17ENTRY_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ENTRY_STATE_PUBLISHED\x10\x01\x12\x15\n" +
	"\x11ENTRY_STATE_DRAFT\x10\x022\xcb\x03\n" +
	"\rLocaleService\x12F\n" +
	"\vGetSnapshot\x12\x1a.locale.v1.SnapshotRequest\x1a\x1b.locale.v1.SnapshotResponse\x12L\n" +
	"\x13GetAvailableLocales\x12\x10.locale.v1.Empty\x1a#.locale.v1.AvailableLocalesResponse\x12:\n" +
	"\x05Watch\x12\x17.locale.v1.WatchRequest\x1a\x16.locale.v1.UpdateEvent0\x01\x12I\n" +
	"\n" +
	"SetEntries\x12\x1c.locale.v1.SetEntriesRequest\x1a\x1d.locale.v1.SetEntriesResponse\x12I\n" +
	"\n" +
	"ListDrafts\x12\x1c.locale.v1.ListDraftsRequest\x1a\x1d.locale.v1.ListDraftsResponse\x12R\n" +
	"\rPublishDrafts\x12\x1f.locale.v1.PublishDraftsRequest\x1a .locale.v1.PublishDraftsResponseBSZQgithub.com/txnet/i18n-platform/services/locale-service/internal/localev1;localev1b\x06proto3"

var (
	file_locale_v1_locale_proto_rawDescOnce sync.Once
	file_locale_v1_locale_proto_rawDescData []byte
)

func file_locale_v1_locale_proto_rawDescGZIP() []byte {
	file_locale_v1_locale_proto_rawDescOnce.Do(func() {
		file_locale_v1_locale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_locale_v1_locale_proto_rawDesc), len(file_locale_v1_locale_proto_rawDesc)))
	})
	return file_locale_v1_locale_proto_rawDescData
}

var file_locale_v1_locale_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_locale_v1_locale_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_locale_v1_locale_proto_goTypes = []any{
	(EntryState)(0),                  // 0: locale.v1.EntryState
	(*SnapshotRequest)(nil),          // 1: locale.v1.SnapshotRequest
	(*SnapshotResponse)(nil),         // 2: locale.v1.SnapshotResponse
	(*NamespaceData)(nil),            // 3: locale.v1.NamespaceData
	(*WatchRequest)(nil),             // 4: locale.v1.WatchRequest
	(*UpdateEvent)(nil),              // 5: locale.v1.UpdateEvent
	(*AvailableLocalesResponse)(nil), // 6: locale.v1.AvailableLocalesResponse
	(*LocaleMeta)(nil),               // 7: locale.v1.LocaleMeta
	(*SetEntriesRequest)(nil),        // 8: locale.v1.SetEntriesRequest
	(*SetEntriesResponse)(nil),       // 9: locale.v1.SetEntriesResponse
	(*ListDraftsRequest)(nil),        // 10: locale.v1.ListDraftsRequest
	(*DraftEntry)(nil),               // 11: locale.v1.DraftEntry
	(*ListDraftsResponse)(nil),       // 12: locale.v1.ListDraftsResponse
	(*PublishDraftsRequest)(nil),     // 13: locale.v1.PublishDraftsRequest
	(*PublishDraftsResponse)(nil),    // 14: locale.v1.PublishDraftsResponse
	(*Empty)(nil),                    // 15: locale.v1.Empty
	nil,                              // 16: locale.v1.SnapshotResponse.NamespacesEntry
	nil,                              // 17: locale.v1.NamespaceData.EntriesEntry
	nil,                              // 18: locale.v1.SetEntriesRequest.EntriesEntry
}
var file_locale_v1_locale_proto_depIdxs = []int32{
	16, // 0: locale.v1.SnapshotResponse.namespaces:type_name -> locale.v1.SnapshotResponse.NamespacesEntry
	17, // 1: locale.v1.NamespaceData.entries:type_name -> locale.v1.NamespaceData.EntriesEntry
	2,  // 2: locale.v1.UpdateEvent.full_snapshot:type_name -> locale.v1.SnapshotResponse
	7,  // 3: locale.v1.AvailableLocalesResponse.locales:type_name -> locale.v1.LocaleMeta
	18, // 4: locale.v1.SetEntriesRequest.entries:type_name -> locale.v1.SetEntriesRequest.EntriesEntry
	0,  // 5: locale.v1.SetEntriesRequest.state:type_name -> locale.v1.EntryState
	11, // 6: locale.v1.ListDraftsResponse.drafts:type_name -> locale.v1.DraftEntry
	3,  // 7: locale.v1.SnapshotResponse.NamespacesEntry.value:type_name -> locale.v1.NamespaceData
	1,  // 8: locale.v1.LocaleService.GetSnapshot:input_type -> locale.v1.SnapshotRequest
	15, // 9: locale.v1.LocaleService.GetAvailableLocales:input_type -> locale.v1.Empty
	4,  // 10: locale.v1.LocaleService.Watch:input_type -> locale.v1.WatchRequest
	8,  // 11: locale.v1.LocaleService.SetEntries:input_type -> locale.v1.SetEntriesRequest
	10, // 12: locale.v1.LocaleService.ListDrafts:input_type -> locale.v1.ListDraftsRequest
	13, // 13: locale.v1.LocaleService.PublishDrafts:input_type -> locale.v1.PublishDraftsRequest
	2,  // 14: locale.v1.LocaleService.GetSnapshot:output_type -> locale.v1.SnapshotResponse
	6,  // 15: locale.v1.LocaleService.GetAvailableLocales:output_type -> locale.v1.AvailableLocalesResponse
	5,  // 16: locale.v1.LocaleService.Watch:output_type -> locale.v1.UpdateEvent
	9,  // 17: locale.v1.LocaleService.SetEntries:output_type -> locale.v1.SetEntriesResponse
	12, // 18: locale.v1.LocaleService.ListDrafts:output_type -> locale.v1.ListDraftsResponse
	14, // 19: locale.v1.LocaleService.PublishDrafts:output_type -> locale.v1.PublishDraftsResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_locale_v1_locale_proto_init() }
func file_locale_v1_locale_proto_init() {
	if File_locale_v1_locale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_locale_v1_locale_proto_rawDesc), len(file_locale_v1_locale_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_locale_v1_locale_proto_goTypes,
		DependencyIndexes: file_locale_v1_locale_proto_depIdxs,
		EnumInfos:         file_locale_v1_locale_proto_enumTypes,
		MessageInfos:      file_locale_v1_locale_proto_msgTypes,
	}.Build()
	File_locale_v1_locale_proto = out.File
	file_locale_v1_locale_proto_goTypes = nil
	file_locale_v1_locale_proto_depIdxs = nil
}
