version: "3.8"

services:
  traefik-registry:
    image: ${DOCKER_REGISTRY}/traefik:v2.10
    container_name: traefik_registry
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # تنظیم پورت‌های داخلی تریفیک
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"

      # تنظیمات Let's Encrypt (استفاده از HTTP Challenge برای سازگاری با CDN)
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # خواندن پورت‌های متصل به سرور از فایل .env
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data:/letsencrypt
    networks:
      - registry_net
    restart: always

  registry:
    image: ${DOCKER_REGISTRY}/registry:2
    container_name: docker_registry
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - registry_net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.${DOMAIN_NAME}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"

      # درخواست گواهینامه SSL از تریفیک
      - "traefik.http.routers.registry.tls.certresolver=myresolver"

      # تنظیم میدل‌ور احراز هویت
      - "traefik.http.routers.registry.middlewares=registry-auth"
      - "traefik.http.middlewares.registry-auth.basicauth.users=${REGISTRY_AUTH_USER}"

      # پورت داخلی کانتینر
      - "traefik.http.services.registry.loadbalancer.server.port=5000"

networks:
  registry_net:
    driver: bridge

volumes:
  registry_data:
    name: registry_standalone_data
