global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: "bale_messenger"

receivers:
  - name: "bale_messenger"
    telegram_configs:
      - api_url: "https://tapi.bale.ai"
        bot_token_file: "/run/secrets/bale_token"
        chat_id: 1404102841
        parse_mode: "HTML"
