#!/usr/bin/env -S npx tsx
/**
 * locale-sdk-gen (TypeScript) — generates a `.d.ts` per namespace from the
 * reference language's snapshot, so `t("auth", "loginTitle")` call sites get
 * autocomplete / compile errors on typo'd keys.
 *
 * Only the *shape* (key names) is generated, never the content — cross-language
 * key-parity is a separate CI check (locales/scripts/validate.ts).
 *
 * Run it from a consuming service as a prebuild step, pointing at that service's
 * own vendored client. This reference copy imports the canonical client:
 *
 *   cd i18n-platform/clients/node
 *   npx tsx ../../codegen/ts/generate.ts --scope frontend --out ../../.generated/i18n
 *
 * fail-soft: if locale-service is unreachable but an earlier OUT_DIR exists, keep
 * it and warn; otherwise exit non-zero.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createLocaleClient } from "../../clients/node/client";

function arg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const REFERENCE_LANG = arg("lang", "fa"); // project reference language is always fa
const SCOPE = arg("scope", "frontend");
const ADDR = process.env.LOCALE_SERVICE_ADDR ?? "localhost:50051";
const OUT_DIR = arg("out", join(process.cwd(), ".generated", "i18n"));

function typeName(ns: string): string {
  const base = ns.replace(/[^a-zA-Z0-9]+/g, "_");
  return base.charAt(0).toUpperCase() + base.slice(1) + "Translations";
}

async function main() {
  const client = createLocaleClient({ addr: ADDR, scope: SCOPE, preloadLangs: [], defaultLang: REFERENCE_LANG });
  let snapshot;
  try {
    snapshot = await client.snapshot(REFERENCE_LANG);
  } catch (err) {
    client.close();
    if (existsSync(OUT_DIR)) {
      console.warn(`[locale-sdk-gen] locale-service (${ADDR}) unreachable; keeping existing ${OUT_DIR}. (${err})`);
      return;
    }
    console.error(`[locale-sdk-gen] locale-service unreachable and no previous ${OUT_DIR} — nothing to generate.`);
    process.exit(1);
  }

  mkdirSync(OUT_DIR, { recursive: true });
  for (const [ns, data] of Object.entries(snapshot.namespaces)) {
    const keys = Object.keys(data.entries).sort();
    const body = keys.map((k) => `  ${JSON.stringify(k)}: string;`).join("\n");
    writeFileSync(
      join(OUT_DIR, `${ns.replace(/\//g, "__")}.d.ts`),
      `// AUTO-GENERATED by locale-sdk-gen — do not edit\n` +
        `// source: locale-service (${ADDR}), scope: ${SCOPE}, ref lang: ${REFERENCE_LANG}, version: ${snapshot.version}\n` +
        `export interface ${typeName(ns)} {\n${body}\n}\n`,
    );
    console.log(`[locale-sdk-gen] wrote ${ns} (${keys.length} keys)`);
  }
  client.close();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
