version: "3.8"

services:
  3eora-mitm-proxy:
    container_name: 3eora-mitm-proxy
    build:
      context: ./code
      dockerfile: Dockerfile.dev
    volumes:
      - ./code:/app
      - gopath:/go
      - gocache:/root/.cache/go-build
    working_dir: /app
    environment:
      - GOPATH=/go
      - GOCACHE=/root/.cache/go-build
      - GOPROXY=https://goproxy.cn,direct
      - GOSUMDB=off
      - CGO_ENABLED=0
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=${S3_REGION}
      - LISTEN_PORT=${LISTEN_PORT}
      - CA_KEY=${CA_KEY}
      - CA_CERT=${CA_CERT}
      - SOCKS_PROXY=${SOCKS_PROXY}
      - SOCKS_PROXY_USER=${SOCKS_PROXY_USER}
      - SOCKS_PROXY_PASS=${SOCKS_PROXY_PASS}
    command: >
      sh -c "
      [ ! -f go.mod ] && go mod init txnet || true;
      air
      "
    networks:
      txnet-network: {}
      private_backend_network:
        ipv4_address: 172.22.100.10
volumes:
  gopath:
  gocache:

networks:
  txnet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

  private_backend_network:
    external: true
    #name: private_backend_network
