#!/usr/bin/env python3
"""Generate site-pwa/src/generated/wire.ts from contracts/ (ADR-0036, C-04, C-08).

`site-pwa` is not in the Nx workspace and cannot import `shared-core`. It reads
the same language-neutral contracts the backend and Go are held to instead:
every object block of the sources below becomes one `as const` object, keyed as
in the JSON (`note` entries dropped, list blocks skipped).

The output is deterministic — source order, no timestamp — so
`python3 tools/contracts.py` fails when the committed file is stale, the same
way CI's `git diff --exit-code` gates the i18n constants.

    python3 tools/wire-gen.py          write the file
    python3 tools/wire-gen.py --check  exit 1 when the committed file differs
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = [
    ROOT / "contracts" / "http" / "wire.json",
    ROOT / "contracts" / "realtime" / "events.json",
]
OUT = ROOT / "site-pwa" / "src" / "generated" / "wire.ts"


def _block(export: str, source: str, key: str, obj: dict) -> list[str]:
    lines = [f"/** `{source}` -> `{key}`. */", f"export const {export} = {{"]
    for k, v in obj.items():
        if k == "note":
            continue
        lines.append(f"  {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)},")
    lines.append("} as const;")
    return lines


def render() -> str:
    out = [
        "// AUTO-GENERATED by tools/wire-gen.py from contracts/ — do not edit.",
        "// Regenerate with `python3 tools/wire-gen.py`; `python3 tools/contracts.py` fails when this is stale.",
        "/* eslint-disable */",
        "",
    ]
    for src in SOURCES:
        rel = src.relative_to(ROOT).as_posix()
        data = json.loads(src.read_text(encoding="utf-8"))
        for key, value in data.items():
            if isinstance(value, dict):
                out += _block(key[0].upper() + key[1:], rel, key, value)
                out.append("")
    return "\n".join(out).rstrip() + "\n"


def stale() -> bool:
    return not OUT.exists() or OUT.read_text(encoding="utf-8") != render()


def main() -> int:
    if "--check" in sys.argv:
        if stale():
            print(f"{OUT.relative_to(ROOT)} is stale — run python3 tools/wire-gen.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
