storage:
  dbPath: /data/db


net:
  port: 27098 # پورتی که گفتی
  bindIp: 0.0.0.0

security:
  authorization: enabled
  keyFile: /data/configdb/mongodb.key # این خط حیاتی است

replication:
  replSetName: rs0 # نام رپلیکا ست اینجا تعریف می‌شود