version: "3.8"

services:
  postgres:
    image: ${DOCKER_REGISTRY}/postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      # داینامیک شدن مقادیر یوزر و دیتابیس
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - glitchtip_postgres_data:/var/lib/postgresql/data
    networks:
      - private_backend_network

  redis:
    image: ${DOCKER_REGISTRY}/redis:7-alpine
    restart: unless-stopped
    volumes:
      - glitchtip_redis_data:/data
    networks:
      - private_backend_network

  # کانتینر جدید برای انجام کارهای راه‌اندازی
  setup:
    image: ${DOCKER_REGISTRY}/glitchtip/glitchtip:v4.0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DJANGO_SUPERUSER_EMAIL=${GLITCHTIP_ADMIN_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${GLITCHTIP_ADMIN_PASS}
    # اجرای همزمان مایگریشن و ساخت ادمین، سپس خروج موفق
    command: >
      bash -c "./manage.py migrate && ./manage.py createsuperuser --noinput || true"
    networks:
      - private_backend_network

  web:
    image: ${DOCKER_REGISTRY}/glitchtip/glitchtip:v4.0
    restart: unless-stopped
    depends_on:
      # وب فقط زمانی اجرا می‌شود که کانتینر setup کارش با موفقیت تمام شده باشد
      setup:
        condition: service_completed_successfully
    environment:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glitchtip_${ENV_NAME}.rule=Host(`${GLITCHTIP_ROUTER_HOST}`)"
      - "traefik.http.services.glitchtip_${ENV_NAME}.loadbalancer.server.port=8000"
    networks:
      - private_backend_network

  worker:
    image: ${DOCKER_REGISTRY}/glitchtip/glitchtip:v4.0
    restart: unless-stopped
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      # ورکر هم منتظر پایان کار setup می‌ماند
      setup:
        condition: service_completed_successfully
    environment:
    networks:
      - private_backend_network

volumes:
  glitchtip_postgres_data:
  glitchtip_redis_data:

networks:
  private_backend_network:
    external: true
    name: private_backend_network
